on:
  push:
    branches:
      - goodpractice
name: Good Practice

jobs:
 
  Good-practice:
    ## run scheduled jobs only on main repo - do not run a duplicate job for merges etc. Do not run if commit messages include any of 'worksave' or 'skip-ci'
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.image }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }} - ${{ matrix.config.bioc }} - ${{ matrix.config.image }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - { os: windows-latest, r: 'release', bioc: 'devel'}
          - { os: macOS-latest, r: 'release', bioc: 'devel'}
          # - { os: ubuntu-latest, r: 'release', image: 'bioconductor/bioconductor_docker:devel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo ⬇️
        uses: actions/checkout@v2

      - name: Set up R ▶️
        uses: r-lib/actions/setup-r@master
        if: matrix.config.image == null
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install and run goodpractice
        run: |
          install.packages("goodpractice")
          res <- goodpractice::gp()
          res
          dir.create('gp')
          saveRDS(res, file = 'gp/res.rds')
        shell: Rscript {0}

      - name: Upload results ⬆️
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: gp
