on:
  push:
    branches: 
      - bioc_master

name: "Push to Bioconductor"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo ⬇️
        uses: actions/checkout@v2
  
      - name: Push to Bioconductor
        run: |
          mkdir log
          touch log/log.txt
          mkdir ~/.ssh
          cp .github/config ~/.ssh/config
          wd=$PWD
          cd ~/.ssh
          ssh-agent /bin/sh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_KEY"
          ssh-keyscan $BIOC_HOST > ~/.ssh/known_hosts
          cd $wd
          git config user.name 'Al J Abadi'
          git config user.email 'al.jal.abadi@gmail.com'
          git remote add bioc git@git.bioconductor.org:packages/mixOmics.git

          git checkout -b current_branch

          echo "\$git fetch bioc master" &>> log/log.txt
          git fetch bioc master &>> log/log.txt

          git checkout -b biocmaster
          echo "\$git reset --hard bioc/master" &>> log/log.txt
          git reset --hard bioc/master &>> log/log.txt

          git checkout current_branch

          echo "\$git log biocmaster..current_branch --pretty=format:\"%s\"" &>> log/log.txt
          git log biocmaster..current_branch --pretty=format:"%s" &>> log/log.txt

          #git push bioc current_branch:master  &>> log/log.txt
        env:
          SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY_AL }}
          BIOC_HOST: ${{ secrets.BIOC_HOST }}


      - name: Diagnostics
        if: failure()
        run: |
          ssh -T git@git.bioconductor.org | sed -ne '/packages\/mixOmics$/p' &>> log/log.txt
          echo "\$git fetch -v"  &>> log/log.txt
          git fetch -v  &>> log/log.txt
          echo "\$git remote -v"  &>> log/log.txt
          git remote -v  &>> log/log.txt

      - name: Upload Files
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: log
          path: log
